# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa9af9f2b1492805a635488094942514742f5e575e95d348d698a1bb772f263e2443daa3eb679d59ef57b15855d4e015b25cdf14e23e4ccf0e6737cf7a0df9b2

test:
  secret_key_base: 9ae3a6b2c6db112c8bad21ec96055654cc0d8da755401beb3754dbe771ff82050676f2bd76d31c772b0eb65da51f92d71ca9483e5310008bd9aa346e3bb45bdb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
